default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prc4_development
  username: rails_dev
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: prc4_test
  host: localhost
  port: 5432
  username: rails_dev
  password: postgres

production:
  <<: *default
  database: prc4_production
  username: prc4
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
