name: Testes
on:
  push:
    branches:
      - jemisson
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run RSpec
      run: RAILS_ENV=test bundle exec rspec
